여기는 마크다운 셀 **입력**입니다.
# 1단계 제목
## 2단계 제목
### 3단계 제목

목록을 표현할 수도 있습니다.
- 테스트 1
- 테스트 2

In [5]:
import numpy as np

In [8]:
data1 = [0,1,2,3,4,5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [9]:
a1.dtype

dtype('int32')

In [11]:
data2 = [1,0.3, "string"]
a2 = np.array(data2)
a2

array(['1', '0.3', 'string'], dtype='<U32')

In [12]:
data2 = [0.1, 5, 4, 12, 0.5]
a2 = np.array(data2)
a2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [13]:
a2.dtype

dtype('float64')

In [14]:
np.array([0.5, 2, 0.01, 8])

array([0.5 , 2.  , 0.01, 8.  ])

In [15]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [18]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [20]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
b1 = np.arange(12).reshape(4,3)
b1.shape

(4, 3)

In [23]:
b2 = np.arange(5)
b2.shape

(5,)

In [24]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [26]:
np.linspace(0, np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [27]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [30]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [31]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
np.array(['1.5', '0.62', '2', '3.14', '3.141592'])

array(['1.5', '0.62', '2', '3.14', '3.141592'], dtype='<U8')

In [36]:
str_a1 = np.array(['1.567','0.123', '5.123', '9', '8'])
num_a1 = str_a1.astype(float)
num_a1

array([1.567, 0.123, 5.123, 9.   , 8.   ])

In [37]:
str_a1.dtype

dtype('<U5')

In [38]:
num_a1.dtype

dtype('float64')

In [39]:
str_a2 = np.array(['1','2','3'])
num_a2 = str_a2.astype(int)
num_a2

array([1, 2, 3])

In [40]:
num_a2.dtype

dtype('int32')

In [41]:
str_a2.dtype

dtype('<U1')

In [42]:
num_f1 = np.array([10, 0.5, 4.7])
num_i1 = num_f1.astype(int)
num_i1

array([10,  0,  4])

In [43]:
np.random.rand(2, 3)

array([[0.98470388, 0.16152885, 0.84189944],
       [0.10206379, 0.33520609, 0.21077016]])

In [44]:
np,random.rand(0)

NameError: name 'random' is not defined

In [45]:
np.random.rand()

0.6217590078949182

In [46]:
np.random.rand(2,3,4)

array([[[0.1165889 , 0.88300046, 0.75934078, 0.71149408],
        [0.74392912, 0.69741808, 0.04865267, 0.79003071],
        [0.26606714, 0.75513719, 0.58818756, 0.31993536]],

       [[0.31968078, 0.85977419, 0.19885451, 0.30067557],
        [0.17383622, 0.98443486, 0.27679107, 0.87893788],
        [0.40223984, 0.66584639, 0.77722483, 0.72364284]]])

In [47]:
np.random.randint(10, size=(3,4))

array([[6, 8, 0, 4],
       [3, 7, 7, 8],
       [6, 7, 7, 4]])

In [51]:
for i in range(50):
  print(np.random.randint(1, 30), end=' ')

27 22 8 16 4 12 11 26 8 17 22 22 19 5 25 7 16 17 4 20 12 9 9 26 7 2 18 8 27 12 14 14 25 29 21 6 11 6 16 29 24 12 25 28 26 19 19 14 19 6 

In [52]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1,2,3,4])

In [53]:
arr1+arr2

array([11, 22, 33, 44])

In [54]:
arr2*2

array([2, 4, 6, 8])

In [55]:
2*arr2

array([2, 4, 6, 8])

In [56]:
arr2**2

array([ 1,  4,  9, 16])

In [57]:
arr1*arr2

array([ 10,  40,  90, 160])

In [58]:
arr1/arr2

array([10., 10., 10., 10.])

In [59]:
arr1/(arr2**2)

array([10.        ,  5.        ,  3.33333333,  2.5       ])

In [60]:
arr1>20

array([False, False,  True,  True])

In [61]:
arr3 = np.arange(5)

In [62]:
arr3

array([0, 1, 2, 3, 4])

In [63]:
[arr3.sum(), arr3.mean()]

[10, 2.0]

In [64]:
[arr3.std(), arr3.var()]

[1.4142135623730951, 2.0]

In [65]:
[arr3.min(), arr3.max()]

[0, 4]

In [66]:
arr4 = np.arange(1, 5)
arr4

array([1, 2, 3, 4])

In [67]:
arr4.cumsum()

array([ 1,  3,  6, 10])

In [68]:
arr4.cumprod()

array([ 1,  2,  6, 24])

In [69]:
A = np.array([0,1,2,3]).reshape(2,2)

In [70]:
A

array([[0, 1],
       [2, 3]])

In [71]:
B = np.array([3, 2, 0, 1]).reshape(2,2)

In [72]:
B

array([[3, 2],
       [0, 1]])

In [73]:
A.dot(B)

array([[0, 1],
       [6, 7]])

In [74]:
np.dot(A,B)

array([[0, 1],
       [6, 7]])

In [75]:
A.transpose()

array([[0, 2],
       [1, 3]])

In [77]:
np.transpose(A)

array([[0, 2],
       [1, 3]])

In [78]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [79]:
np.linalg.det(A)

-2.0

In [80]:
a = np.array([0, 10, 20, 30, 40, 50])

In [81]:
a[0]

0

In [82]:
a[4]

40

In [83]:
a[5]=70

In [84]:
a

array([ 0, 10, 20, 30, 40, 70])

In [87]:
a[[1,3,4]]

array([10, 30, 40])

In [88]:
a2 = np.arange(10, 100, 10).reshape(3,3)

In [89]:
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [90]:
a2[0, 2]

30

In [91]:
a2[2,2]

90

In [92]:
a2[1]

array([40, 50, 60])

In [93]:
a2[1] = np.array([45,55,65])

In [94]:
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 90]])

In [95]:
a2[1] = [47, 57, 67]

In [96]:
a2

array([[10, 20, 30],
       [47, 57, 67],
       [70, 80, 90]])

In [97]:
a2[[0,2],[0,1]]

array([10, 80])

In [98]:
a = np.array([1,2,3,4,5,6])
a[a>3]

array([4, 5, 6])

In [99]:
a[np.array([False, False, False, True, True, True])]

array([4, 5, 6])

In [100]:
a[a%2==0]

array([2, 4, 6])

In [101]:
b1 = np.array([0, 10, 20, 30, 40, 50])
b1[1:4]

array([10, 20, 30])

In [102]:
b1[:3]

array([ 0, 10, 20])

In [103]:
b1[2:]

array([20, 30, 40, 50])

In [104]:
b1[2:5] = np.array([25, 35, 45])

In [105]:
b1

array([ 0, 10, 25, 35, 45, 50])

In [106]:
b1[3:6]=60
b1

array([ 0, 10, 25, 60, 60, 60])

In [107]:
b2 = np.arange(10, 100, 10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [108]:
b2[1:3, 1:3]

array([[50, 60],
       [80, 90]])

In [109]:
b2[:3, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [110]:
b2[1:, 1:]

array([[50, 60],
       [80, 90]])

In [111]:
b2[:, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [112]:
b2[1][0:2]

array([40, 50])

In [113]:
b2[1][:2]

array([40, 50])

In [114]:
b2[0:2, 1:3] = np.array([[25, 35], [55, 65]])
b2

array([[10, 25, 35],
       [40, 55, 65],
       [70, 80, 90]])